name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_SOCIAL_API_BASE_URL: ${{ vars.VITE_SOCIAL_API_BASE_URL }}
          VITE_NUTRITION_API_BASE_URL: ${{ vars.VITE_NUTRITION_API_BASE_URL }}
          VITE_CHAT_API_BASE_URL: ${{ vars.VITE_CHAT_API_BASE_URL }}
          VITE_NOTIFICATION_API_BASE_URL: ${{ vars.VITE_NOTIFICATION_API_BASE_URL }}
          VITE_TRAINING_API_BASE_URL: ${{ vars.VITE_TRAINING_API_BASE_URL }}
          VITE_AUTH_API_BASE_URL: ${{ vars.VITE_AUTH_API_BASE_URL }}
          VITE_PROFESSIONAL_MANAGEMENT_API_BASE_URL: ${{ vars.VITE_PROFESSIONAL_MANAGEMENT_API_BASE_URL }}

          VITE_ENCRYPTION_KEY: ${{ secrets.VITE_ENCRYPTION_KEY }}

          VITE_FIREBASE_API_KEY:                ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN:            ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID:             ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET:         ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID:    ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID:                 ${{ secrets.VITE_FIREBASE_APP_ID }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_POND_0C643C00F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_POND_0C643C00F }}
          action: "close"
